name: Build desktop app

on:
  push:
    tags: ['v*.*.*']
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
        python-version: ['3.11']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: macOS system deps (best-effort)
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install cairo pango gobject-introspection || true

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Create .env from repository secrets
        shell: bash
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          ENV_PASSPHRASE: ${{ secrets.ENV_PASSPHRASE }}
          IRONPDF_LICENSE_KEY: ${{ secrets.IRONPDF_LICENSE_KEY }}
          PDF_WARMUP: ${{ secrets.PDF_WARMUP }}
        run: |
          cat > .env <<'EOF'
          DB_HOST=${DB_HOST}
          DB_NAME=${DB_NAME}
          DB_PASSWORD=${DB_PASSWORD}
          DB_PORT=${DB_PORT}
          DB_USER=${DB_USER}
          ENV_PASSPHRASE=${ENV_PASSPHRASE}
          IRONPDF_LICENSE_KEY=${IRONPDF_LICENSE_KEY}
          PDF_WARMUP=${PDF_WARMUP}
          EOF
          chmod 600 .env || true

      - name: Build executable with PyInstaller
        shell: bash
        run: |
          pyinstaller --noconfirm --clean \
            --name "SportsThreadApp" \
            --add-data ".env:." \
            --add-data "sportsthread_logo.png:." \
            app/main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.os }}
          path: |
            dist/SportsThreadApp/**
            !**/*.log
